'use client';

import { useEffect, useState } from 'react';
import Image from 'next/image';
import { Calendar, Clock, Globe2, MapPin, Users, CheckCircle2, Video } from 'lucide-react';

type Meetup = { _id: string; title: string; shortDescription: string; description: string; category: string; coverImage?: string; speakerName: string; speakerRole?: string; speakerOrganization?: string; format: 'online' | 'in-person' | 'hybrid'; date: string; startTime: string; endTime: string; timezone: string; venueName?: string; venueCity?: string; platform?: string; capacity: number; registrations: unknown[]; status: string };
const fallbackImage = 'https://images.unsplash.com/photo-1505373877841-8d25f7d46678?w=1200&auto=format&fit=crop&q=80';

export default function MeetupPage() {
  const [meetups, setMeetups] = useState<Meetup[]>([]); const [selected, setSelected] = useState<Meetup | null>(null); const [loading, setLoading] = useState(true); const [result, setResult] = useState<string | null>(null);
  const load = () => fetch('/api/meetups').then(r => r.json()).then(d => setMeetups(d.meetups || [])).finally(() => setLoading(false));
  useEffect(() => { load(); }, []);
  async function register() { if (!selected) return; const user = JSON.parse(localStorage.getItem('aptivo_user') || '{}'); if (!user.email) return setResult('Please sign in to register.'); const res = await fetch('/api/meetups', { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ meetupId: selected._id, studentEmail: user.email }) }); const data = await res.json(); setResult(data.success ? "You're registered ✓" : data.error || 'Unable to register.'); if (data.success) load(); }
  return <div className="space-y-6 animate-in fade-in duration-300">
    <section className="rounded-3xl bg-gradient-to-r from-emerald-950 via-darkpine-900 to-slate-900 p-7 sm:p-9 text-white"><p className="text-xs font-bold uppercase tracking-[.18em] text-emerald-300">Pillar 1 · Meetup</p><h2 className="mt-2 text-3xl font-black tracking-tight">Learn from people doing the work.</h2><p className="mt-2 max-w-2xl text-sm text-emerald-100/80">Aptivo-curated talks, expert sessions, panels and community events. Discover a session, register, and show up ready.</p></section>
    {loading ? <p className="py-12 text-center text-sm text-slate-400">Loading meetups…</p> : meetups.length === 0 ? <div className="rounded-3xl border border-dashed border-slate-300 bg-slate-50 p-12 text-center"><Calendar className="mx-auto mb-3 h-8 w-8 text-slate-400"/><h3 className="font-bold text-slate-800">No upcoming meetups yet.</h3><p className="mt-1 text-xs text-slate-500">Aptivo is curating the next opportunity.</p></div> : <div className="grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-3">{meetups.map(m => <article key={m._id} className="group overflow-hidden rounded-3xl border border-slate-200/80 bg-slate-50 shadow-soft transition-all hover:bg-white hover:shadow-lg"><div className="relative h-40"><Image src={m.coverImage || fallbackImage} alt="" fill unoptimized className="object-cover transition-transform duration-300 group-hover:scale-105"/><span className="absolute left-3 top-3 rounded-full bg-slate-950/80 px-3 py-1 text-[10px] font-bold text-white backdrop-blur">{m.category}</span></div><div className="space-y-3 p-5"><div><p className="text-xs font-bold text-brand-700">{m.speakerName}{m.speakerOrganization ? ` · ${m.speakerOrganization}` : ''}</p><h3 className="mt-1 text-base font-extrabold text-slate-900">{m.title}</h3><p className="mt-2 line-clamp-2 text-xs leading-relaxed text-slate-600">{m.shortDescription}</p></div><div className="space-y-1.5 rounded-2xl border border-slate-100 bg-white p-3 text-xs text-slate-600"><p className="flex gap-2"><Calendar className="h-3.5 w-3.5 text-emerald-600"/>{m.date}</p><p className="flex gap-2"><Clock className="h-3.5 w-3.5 text-emerald-600"/>{m.startTime} – {m.endTime}</p><p className="flex gap-2">{m.format === 'online' ? <Globe2 className="h-3.5 w-3.5 text-emerald-600"/> : <MapPin className="h-3.5 w-3.5 text-emerald-600"/>}{m.format === 'online' ? `${m.platform || 'Online'} session` : `${m.venueCity || m.venueName || 'In-person'}${m.format === 'hybrid' ? ' + Online' : ''}`}</p><p className="flex gap-2 font-medium text-emerald-700"><Users className="h-3.5 w-3.5"/>{m.registrations.length} / {m.capacity} registered</p></div><button onClick={() => { setSelected(m); setResult(null); }} className="w-full rounded-xl bg-slate-900 py-2.5 text-xs font-bold text-white transition-colors hover:bg-brand-600">View & Register</button></div></article>)}</div>}
    {selected && <div className="fixed inset-0 z-50 flex items-center justify-center bg-slate-900/60 p-4 backdrop-blur-sm"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-3xl border border-slate-100 bg-white p-6 shadow-2xl sm:p-8">{result?.includes('✓') ? <div className="py-10 text-center"><CheckCircle2 className="mx-auto h-12 w-12 text-emerald-600"/><h3 className="mt-3 text-xl font-extrabold">{result}</h3><p className="mt-1 text-sm text-slate-500">{selected.title}<br/>{selected.date} · {selected.startTime}</p><button onClick={() => setSelected(null)} className="mt-6 rounded-xl bg-slate-900 px-5 py-2.5 text-xs font-bold text-white">Done</button></div> : <><button onClick={() => setSelected(null)} className="float-right text-sm text-slate-400">Close</button><p className="text-xs font-bold uppercase tracking-wider text-brand-700">{selected.category}</p><h2 className="mt-1 text-2xl font-black text-slate-900">{selected.title}</h2><p className="mt-3 text-sm leading-relaxed text-slate-600">{selected.description}</p><div className="mt-5 rounded-2xl bg-slate-50 p-4 text-xs text-slate-600"><p className="font-bold text-slate-900">{selected.speakerName}</p><p>{selected.speakerRole}{selected.speakerOrganization ? ` · ${selected.speakerOrganization}` : ''}</p><p className="mt-3 flex gap-2"><Video className="h-3.5 w-3.5"/>{selected.format === 'online' ? selected.platform || 'Online' : selected.venueName || selected.venueCity}</p><p className="mt-1">{selected.date} · {selected.startTime} – {selected.endTime} · {selected.timezone}</p></div>{result && <p className="mt-3 text-xs font-semibold text-rose-600">{result}</p>}<button onClick={register} className="mt-5 w-full rounded-xl bg-brand-600 py-3 text-sm font-bold text-white hover:bg-brand-700">Register</button></>}</div></div>}
  </div>;
}
