'use client';
import Link from 'next/link';
import { ArrowRight, Building2, CheckCircle2, Hammer, Sparkles, Users } from 'lucide-react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const pillars = [
  { name: 'MEETUP', icon: Users, color: 'emerald', title: 'Learn from people doing the work.', body: 'Aptivo-curated talks, panels, expert sessions and workshops. Discover the session, register once, and attend.', href: '/dashboard/meetup', action: 'Explore Meetups' },
  { name: 'BUILD', icon: Hammer, color: 'amber', title: 'Find people and build something real.', body: 'Start a project or join an approved team. Build together, track milestones, and submit work to the verified showcase.', href: '/dashboard/build', action: 'Browse Projects' },
  { name: 'EXPERIENCE', icon: Building2, color: 'blue', title: 'Step inside the environments where it happens.', body: 'Visit workplaces, labs, companies and institutes through Aptivo-led exposure opportunities.', href: '/dashboard/experience', action: 'View Experiences' },
];

export default function LandingPage() {
  return <main className="min-h-screen bg-[#F8FAFC]"><Navbar />
    <section className="relative overflow-hidden border-b border-emerald-100 bg-gradient-to-b from-emerald-50 via-white to-slate-50 py-20 sm:py-28"><div className="pointer-events-none absolute inset-0 bg-[radial-gradient(#22c55e_1px,transparent_1px)] [background-size:24px_24px] opacity-10"/><div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full border border-emerald-200 bg-emerald-100/80 px-4 py-1.5 text-xs font-bold text-emerald-900"><Sparkles className="h-3.5 w-3.5"/> Aptivo Connect · Opportunity engine</div><h1 className="mt-6 text-5xl font-black leading-[1.05] tracking-tight text-slate-900 sm:text-7xl">Meetup. Build.<br/><span className="bg-gradient-to-r from-brand-600 to-emerald-800 bg-clip-text text-transparent">Experience.</span></h1><p className="mt-6 max-w-2xl text-base leading-relaxed text-slate-600 sm:text-lg">Aptivo discovers, curates and delivers real opportunities. Students discover, register, participate and build.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/auth/register" className="inline-flex items-center gap-2 rounded-full bg-slate-900 px-6 py-3 text-sm font-bold text-white shadow-md transition-colors hover:bg-brand-700">Join Aptivo <ArrowRight className="h-4 w-4"/></Link><Link href="#pillars" className="rounded-full border border-slate-200 bg-white px-6 py-3 text-sm font-bold text-slate-700 hover:bg-slate-50">Explore the pillars</Link></div></div></div></section>
    <section id="pillars" className="py-20"><div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8"><div className="mb-12 max-w-2xl"><p className="text-xs font-bold uppercase tracking-[.18em] text-brand-700">Three focused pillars</p><h2 className="mt-3 text-3xl font-black tracking-tight text-slate-900 sm:text-4xl">Opportunity, without the clutter.</h2><p className="mt-3 text-sm leading-relaxed text-slate-600">A session, a project, and an exposure visit have distinct workflows—so they should feel distinct too.</p></div><div className="grid gap-6 lg:grid-cols-3">{pillars.map(({name, icon: Icon, color, title, body, href, action}, i) => <article key={name} className="flex flex-col rounded-3xl border border-slate-200/80 bg-white p-7 shadow-soft transition-all hover:-translate-y-1 hover:shadow-lg"><div className={`flex h-12 w-12 items-center justify-center rounded-2xl ${color === 'emerald' ? 'bg-emerald-100 text-emerald-800' : color === 'amber' ? 'bg-amber-100 text-amber-800' : 'bg-blue-100 text-blue-800'}`}><Icon className="h-6 w-6"/></div><p className="mt-6 text-xs font-bold tracking-[.16em] text-slate-500">PILLAR 0{i + 1} · {name}</p><h3 className="mt-2 text-xl font-extrabold text-slate-900">{title}</h3><p className="mt-3 text-sm leading-relaxed text-slate-600">{body}</p><p className="mt-5 flex gap-2 text-xs font-medium text-slate-600"><CheckCircle2 className="h-4 w-4 shrink-0 text-emerald-600"/>Clear registration, capacity and status</p><Link href={href} className="mt-7 inline-flex items-center gap-1.5 text-xs font-bold text-slate-900 hover:text-brand-700">{action}<ArrowRight className="h-3.5 w-3.5"/></Link></article>)}</div></div></section>
    <section className="border-y border-slate-800 bg-slate-950 py-16 text-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:grid-cols-3 sm:px-6 lg:px-8">{pillars.map(p => <div key={p.name}><p className="text-sm font-bold text-emerald-300">{p.name}</p><p className="mt-2 text-sm text-slate-300">{p.title}</p></div>)}</div></section><Footer />
  </main>;
}
