'use client';

import Link from 'next/link';
import { ArrowDownRight, ArrowRight, Building2, Compass, Hammer, Sparkles, UsersRound } from 'lucide-react';
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';

const pillars = [
  { name: 'Meet', title: 'Good conversations move ideas forward.', body: 'Join talks, workshops and small-group sessions with people working in your field.', href: '/dashboard/meetup', icon: UsersRound, tone: 'bg-[#E4EEE8] text-[#174D3A]' },
  { name: 'Build', title: 'Make something with a team.', body: 'Find collaborators, share what you bring and work on projects with a clear purpose.', href: '/dashboard/build', icon: Hammer, tone: 'bg-[#FCE9E3] text-[#A94431]' },
  { name: 'Experience', title: 'See where the work happens.', body: 'Step into companies, labs and workplaces through curated visits and experiences.', href: '/dashboard/experience', icon: Building2, tone: 'bg-[#E4EEE8] text-[#174D3A]' },
];

export default function LandingPage() {
  return <main className="min-h-screen bg-[#F7F6F1] text-[#18201C]"><Navbar/>
    <section className="relative overflow-hidden bg-[#F7F6F1]">
      <div className="pointer-events-none absolute -right-24 -top-32 h-[34rem] w-[34rem] rounded-full border border-[#287A5B]/25 sm:right-0 sm:top-[-10rem]"/><div className="pointer-events-none absolute right-8 top-20 h-80 w-80 rounded-full border border-[#287A5B]/25 sm:right-20"/><div className="pointer-events-none absolute right-32 top-36 h-48 w-48 rounded-full border border-[#287A5B]/20 sm:right-48"/>
      <div className="relative mx-auto grid max-w-7xl items-center gap-10 px-5 py-14 sm:px-8 sm:py-20 lg:min-h-[570px] lg:grid-cols-[1fr_0.9fr] lg:gap-12 lg:px-10">
        <div className="max-w-2xl"><p className="inline-flex items-center gap-2 text-sm font-medium text-[#174D3A]"><span className="grid h-7 w-7 place-items-center rounded-lg bg-[#E4EEE8]"><Sparkles className="h-4 w-4"/></span>Aptivo Connect</p><h1 className="aptivo-display mt-6 text-[3.2rem] font-semibold leading-[.94] sm:text-7xl">Meet.<br/>Build.<br/><span className="text-[#174D3A]">Experience.</span></h1><p className="mt-5 max-w-xl text-base leading-7 text-[#69736D] sm:text-lg">Connect with people, collaborate on work that matters, and find experiences that help you grow.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/auth/register" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-[#E86F51] px-6 text-sm font-semibold text-white transition hover:bg-[#cf5e43] active:scale-[0.98]">Join Connect<ArrowRight className="h-4 w-4"/></Link><Link href="#how-it-works" className="inline-flex min-h-12 items-center gap-2 rounded-full px-5 text-sm font-semibold text-[#174D3A] transition hover:bg-white">See how it works<ArrowDownRight className="h-4 w-4"/></Link></div><div className="mt-9 flex items-center gap-2 text-sm text-[#69736D]"><Compass className="h-4 w-4 text-[#287A5B]"/>Built around real people and real opportunities</div></div>
        <div aria-hidden="true" className="relative mx-auto h-[330px] w-full max-w-[510px] sm:h-[400px]">
          <svg viewBox="0 0 500 400" className="absolute inset-0 h-full w-full text-emerald-300"><path d="M112 202 C170 80 300 60 380 158 C436 226 354 324 258 294 C184 272 174 167 245 132 C302 104 362 152 350 204" fill="none" stroke="currentColor" strokeWidth="1.4" strokeDasharray="4 7"/><path d="M112 202L245 132M112 202L258 294M245 132L380 158M258 294L350 204" fill="none" stroke="currentColor" strokeWidth="1.2"/></svg>
          <div className="absolute left-[11%] top-[43%] grid h-24 w-24 place-items-center rounded-[2rem] bg-[#174D3A] text-white shadow-[0_12px_26px_rgba(24,32,28,.12)] sm:h-28 sm:w-28"><UsersRound className="h-10 w-10"/><span className="sr-only">Meet people</span></div>
          <div className="absolute left-[42%] top-[13%] grid h-20 w-20 place-items-center rounded-[1.7rem] bg-[#FCE9E3] text-[#A94431] shadow-lg sm:h-24 sm:w-24"><Hammer className="h-9 w-9"/><span className="sr-only">Build together</span></div>
          <div className="absolute right-[6%] top-[34%] grid h-20 w-20 place-items-center rounded-[1.7rem] bg-[#E4EEE8] text-[#174D3A] shadow-[0_10px_22px_rgba(24,32,28,.08)] sm:h-24 sm:w-24"><Building2 className="h-9 w-9"/><span className="sr-only">Explore work</span></div>
          <div className="absolute left-[45%] bottom-[8%] grid h-[4.5rem] w-[4.5rem] place-items-center rounded-[1.5rem] bg-white text-[#174D3A] ring-1 ring-[#E4E7E2] shadow-[0_10px_22px_rgba(24,32,28,.08)]"><Sparkles className="h-7 w-7"/></div>
          <span className="absolute left-[5%] top-[22%] h-3 w-3 rounded-full bg-[#287A5B]"/><span className="absolute right-[20%] top-[11%] h-2 w-2 rounded-full bg-[#E86F51]"/><span className="absolute right-[3%] bottom-[20%] h-3 w-3 rounded-full bg-[#287A5B]"/>
          <div className="absolute left-[32%] top-[49%] rounded-full bg-white/95 px-3 py-1.5 text-xs font-medium text-slate-700 shadow-sm ring-1 ring-slate-100">Ideas connect here</div>
        </div>
      </div>
    </section>
    <section id="pillars" className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20 lg:px-10"><div className="mb-9 max-w-2xl"><p className="text-sm font-medium text-emerald-800">A place to move forward</p><h2 className="mt-2 text-3xl font-semibold tracking-tight sm:text-4xl">Meet. Build. Experience.</h2><p className="mt-3 text-base leading-7 text-slate-600">Different ways to find your people and get involved in work that matters to you.</p></div><div className="grid gap-x-10 md:grid-cols-3">{pillars.map(({ name, title, body, href, icon: Icon, tone }) => <article key={name} className="border-t border-slate-200 py-6"><div className={`grid h-11 w-11 place-items-center rounded-xl ${tone}`}><Icon className="h-5 w-5"/></div><p className="mt-5 text-sm font-medium text-slate-500">{name}</p><h3 className="mt-1 text-xl font-semibold leading-snug">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{body}</p><Link href={href} className="mt-5 inline-flex min-h-10 items-center gap-2 text-sm font-semibold text-emerald-800 hover:text-emerald-950">Explore {name}<ArrowRight className="h-4 w-4"/></Link></article>)}</div></section>
    <section id="how-it-works" className="border-y border-emerald-100 bg-emerald-50/60"><div className="mx-auto grid max-w-7xl gap-8 px-5 py-14 sm:px-8 md:grid-cols-[0.8fr_1.2fr] md:items-center md:py-16 lg:px-10"><div><p className="text-sm font-medium text-emerald-800">How Connect works</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">A profile that grows with you.</h2></div><p className="max-w-2xl text-base leading-7 text-slate-700">Take part in meetups, collaborate on projects and join real-world experiences. Your Aptivo profile brings your skills, work and verified participation together as you go.</p></div></section>
    <section className="mx-auto flex max-w-7xl flex-col items-start justify-between gap-6 px-5 py-14 sm:px-8 md:flex-row md:items-center md:py-16 lg:px-10"><div><h2 className="text-2xl font-semibold tracking-tight">Your next step starts with a connection.</h2><p className="mt-2 text-sm text-slate-600">Create your profile and find a way in.</p></div><Link href="/auth/register" className="inline-flex min-h-12 items-center gap-2 rounded-full bg-emerald-800 px-6 text-sm font-semibold text-white transition hover:bg-emerald-900">Get started<ArrowRight className="h-4 w-4"/></Link></section>
    <Footer/>
  </main>;
}
