'use client';

import { ChangeEvent, FormEvent, useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, Building2, Eye, ImagePlus, Pencil, Plus, Search, Users } from 'lucide-react';
import Avatar from '@/components/Avatar';
import MediaImage from '@/components/MediaImage';

type Campus = { _id: string; name: string; university: string; shortName?: string; city?: string; description?: string; logoUrl?: string; active: boolean; visible: boolean; studentCount: number };
type Member = { _id: string; fullName?: string; name?: string; email: string; profilePhoto?: string; avatarUrl?: string; degree?: string; fieldOfStudy?: string; field?: string; currentYear?: string; status?: string };
const blank = { name: '', university: '', shortName: '', city: '', description: '', logoUrl: '', active: true, visible: true };

export default function AdminCampusPage() {
  const [campuses, setCampuses] = useState<Campus[]>([]); const [query, setQuery] = useState(''); const [status, setStatus] = useState<'all' | 'active' | 'inactive'>('all');
  const [form, setForm] = useState(blank); const [editing, setEditing] = useState<Campus | null>(null); const [editorOpen, setEditorOpen] = useState(false); const [members, setMembers] = useState<Member[] | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const load = async () => { const response = await fetch('/api/admin/campus'); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to load campuses.'); setCampuses(data.campuses || []); };
  useEffect(() => { load().catch((err) => setError(err.message)); }, []);
  const filtered = useMemo(() => campuses.filter((campus) => (status === 'all' || (status === 'active' ? campus.active : !campus.active)) && `${campus.name} ${campus.university} ${campus.city || ''}`.toLowerCase().includes(query.toLowerCase())), [campuses, query, status]);
  const openEdit = (campus?: Campus) => { setEditing(campus || null); setForm(campus ? { name: campus.name, university: campus.university, shortName: campus.shortName || '', city: campus.city || '', description: campus.description || '', logoUrl: campus.logoUrl || '', active: campus.active, visible: campus.visible } : blank); setMembers(null); setEditorOpen(true); setError(''); };
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(''); try { const response = await fetch(editing ? `/api/admin/campus/${editing._id}` : '/api/admin/campus', { method: editing ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to save campus.'); setEditorOpen(false); setEditing(null); setForm(blank); await load(); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to save campus.'); } finally { setBusy(false); } };
  const uploadLogo = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; setBusy(true); setError(''); try { const body = new FormData(); body.append('file', file); body.append('category', 'campus-logo'); const response = await fetch('/api/upload', { method: 'POST', body }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to upload logo.'); setForm((value) => ({ ...value, logoUrl: data.url })); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to upload logo.'); } finally { setBusy(false); } };
  const viewMembers = async (campus: Campus) => { setEditing(campus); setEditorOpen(false); setMembers(null); setError(''); try { const response = await fetch(`/api/admin/campus/${campus._id}`); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'Unable to load members.'); setMembers(data.members || []); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load members.'); } };
  return <main className="min-h-screen bg-slate-100 p-4 text-slate-900 sm:p-8"><div className="mx-auto max-w-7xl space-y-6"><header className="flex flex-wrap items-center justify-between gap-3"><div><Link href="/admin" className="mb-3 inline-flex items-center gap-1 text-xs font-semibold text-slate-600 hover:text-slate-900"><ArrowLeft className="h-3.5 w-3.5"/>Admin</Link><h1 className="text-3xl font-bold tracking-tight">Campus</h1><p className="mt-1 text-sm text-slate-600">Manage institutions and their real student communities.</p></div><button onClick={() => openEdit()} className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-slate-900 px-4 text-sm font-bold text-white hover:bg-slate-700"><Plus className="h-4 w-4"/>Add Campus</button></header>
    <section className="grid gap-3 sm:grid-cols-3"><Metric label="Total campuses" value={campuses.length}/><Metric label="Active campuses" value={campuses.filter((item) => item.active).length}/><Metric label="Associated students" value={campuses.reduce((sum, item) => sum + item.studentCount, 0)}/></section>
    <section className="rounded-2xl border border-slate-200 bg-white p-4"><div className="mb-4 flex flex-wrap gap-3"><label className="flex min-h-10 flex-1 items-center gap-2 rounded-xl border border-slate-200 px-3 text-slate-500"><Search className="h-4 w-4"/><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search campus or institution" className="w-full outline-none"/></label><select value={status} onChange={(event) => setStatus(event.target.value as typeof status)} className="rounded-xl border border-slate-200 px-3 text-sm"><option value="all">All status</option><option value="active">Active</option><option value="inactive">Inactive</option></select></div>{error && <p className="mb-3 rounded-lg bg-rose-50 p-3 text-sm text-rose-700">{error}</p>}<div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead className="border-b border-slate-200 text-xs uppercase tracking-wide text-slate-500"><tr><th className="p-3">Campus</th><th className="p-3">City</th><th className="p-3">Students</th><th className="p-3">Status</th><th className="p-3 text-right">Actions</th></tr></thead><tbody>{filtered.map((campus) => <tr key={campus._id} className="border-b border-slate-100"><td className="p-3"><div className="flex items-center gap-3"><MediaImage src={campus.logoUrl} alt="" kind="build" className="h-10 w-10 rounded-lg"/><span><b className="block">{campus.name}</b><small className="text-slate-500">{campus.university}</small></span></div></td><td className="p-3 text-slate-600">{campus.city || '—'}</td><td className="p-3"><span className="inline-flex items-center gap-1"><Users className="h-3.5 w-3.5"/>{campus.studentCount}</span></td><td className="p-3"><span className={campus.active ? 'rounded-full bg-emerald-50 px-2 py-1 text-xs font-semibold text-emerald-800' : 'rounded-full bg-slate-100 px-2 py-1 text-xs font-semibold text-slate-600'}>{campus.active ? 'Active' : 'Inactive'}{!campus.visible && ' · hidden'}</span></td><td className="p-3 text-right"><button onClick={() => viewMembers(campus)} className="mr-2 rounded-lg p-2 hover:bg-slate-100" aria-label="View members"><Eye className="h-4 w-4"/></button><button onClick={() => openEdit(campus)} className="rounded-lg p-2 hover:bg-slate-100" aria-label="Edit campus"><Pencil className="h-4 w-4"/></button></td></tr>)}</tbody></table>{filtered.length === 0 && <div className="py-12 text-center text-sm text-slate-500">No campuses match this view.</div>}</div></section>
    {editorOpen && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><form onSubmit={submit} className="max-h-[90dvh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-bold">{editing ? 'Edit campus' : 'Add campus'}</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Campus name" value={form.name} onChange={(name) => setForm({ ...form, name })}/><Field label="University / institution" value={form.university} onChange={(university) => setForm({ ...form, university })}/><Field label="Short name" value={form.shortName} onChange={(shortName) => setForm({ ...form, shortName })}/><Field label="City" value={form.city} onChange={(city) => setForm({ ...form, city })}/><label className="sm:col-span-2 text-sm font-semibold">Description<textarea value={form.description} onChange={(event) => setForm({ ...form, description: event.target.value })} className="mt-1 min-h-24 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label><div className="sm:col-span-2"><p className="text-sm font-semibold">Campus logo</p><div className="mt-2 flex items-center gap-3">{form.logoUrl ? <MediaImage src={form.logoUrl} alt="Campus logo" kind="build" className="h-14 w-14 rounded-xl"/> : <div className="grid h-14 w-14 place-items-center rounded-xl bg-slate-100"><Building2 className="h-5 w-5"/></div>}<label className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm"><ImagePlus className="h-4 w-4"/>Upload<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={uploadLogo} className="hidden"/></label></div></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={(event) => setForm({ ...form, active: event.target.checked })}/>Active</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.visible} onChange={(event) => setForm({ ...form, visible: event.target.checked })}/>Visible in student Campus</label></div><div className="mt-6 flex justify-end gap-2"><button type="button" onClick={() => { setEditorOpen(false); setEditing(null); setForm(blank); }} className="rounded-xl px-4 py-2 text-sm">Cancel</button><button disabled={busy} className="rounded-xl bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">{busy ? 'Saving…' : 'Save campus'}</button></div></form></div>}
    {members && editing && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><section className="max-h-[90dvh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><h2 className="text-xl font-bold">{editing.name} members</h2><p className="text-sm text-slate-500">Real accounts associated with this campus.</p></div><button onClick={() => setMembers(null)} className="rounded-lg px-3">Close</button></div><div className="mt-5 divide-y">{members.map((member) => <Link href={`/profile/${member._id}`} key={member._id} className="flex items-center gap-3 py-3 hover:bg-slate-50"><Avatar src={member.profilePhoto || member.avatarUrl} name={member.fullName || member.name} size={38}/><span className="min-w-0"><b className="block truncate text-sm">{member.fullName || member.name}</b><small className="block truncate text-slate-500">{member.email} · {[member.degree, member.fieldOfStudy || member.field, member.currentYear].filter(Boolean).join(' · ') || 'Profile incomplete'}</small></span></Link>)}{members.length === 0 && <p className="py-8 text-center text-sm text-slate-500">No associated student accounts yet.</p>}</div></section></div>}
  </div></main>;
}
function Metric({ label, value }: { label: string; value: number }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><p className="text-xs font-semibold uppercase tracking-wide text-slate-500">{label}</p><p className="mt-1 text-3xl font-bold">{value}</p></div>; }
function Field({ label, value, onChange }: { label: string; value: string; onChange: (value: string) => void }) { return <label className="text-sm font-semibold">{label}<input required={label === 'Campus name' || label === 'University / institution'} value={value} onChange={(event) => onChange(event.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 p-3 font-normal"/></label>; }
